### ISSUE TITLE
taken verdelen wie wat

### ISSUE THREAD

**Issue by Juaopteinde** [Juaopteinde/gimma-bouwen#4]
We moeten taken verdelen, als iedereen aangeeft wat je leuk lijkt om te doen in de comments zou dat top zijn.

Denk aan:
Frontend dev - alles waar de speler direct mee interact, knopjes, de camera, etc.
Backend dev - alles waar de speler niet direct mee interact, de code om de knopjes te laten werken enzo
Designer - ontwerpen van de wereld
Tester- testen van de game

Of iets anders wat je wilt doen natuurlijk

**Comment by pinkodingle** [comment]
ik denk dat het handig is als ik of designer of tester word

**Comment by appie857** [comment]
Ik vind backend frontend en design goed dus eigenlijk gewoon alles

**Comment by timmeej** [comment]
Testen doe ik sws graag. Ik weet alleen niet waar ik echt beter in zou zijn qua coderen. Design zou ik ook wel aan willen helpen
