### ISSUE TITLE
Engine kiezen

### ISSUE THREAD

**Issue by Juaopteinde** [Juaopteinde/gimma-bouwen#6]
Over het algemeen zijn er 3 game engines die veelgebruikt zijn:

- **Godot**
- **Unreal**
- **Unity**

Van wat ik online zie over de drie zijn dit een beetje de pros en cons:

**Godot**

Pros:
-Open-Source, maakt het makkelijk om features aan te passen of toe te voegen. En je zal nooit geld hoeven te betalen aan Godot om geld van je game te verdienen.

Cons:
-Weinig ingebouwde functies vergeleken Unity & Unreal, waardoor het ook meer werk kan worden.

**Unity**

Pros:
-Goed gedocumenteerd, je kan alles online vinden.
-Veel ingebouwde functies, kan het makkelijker maken om iets uit de grond te stampen.

Cons:
-Niet open-source, dus als we tegen een fundamenteel probleem aanlopen kan het erg lastig worden om op te lossen. Onwaarschijnlijk om voor te komen met simpelere projecten.
-Uiteindelijk dokken als we geld willen maken met een game.
-Veel ingebouwde functies kan het ook onoverzichtelijk en langzamer maken.

**Unreal**

Pros:
-Makkelijk uitbreidbaar naar gigantische teams (misschien niet echt van toepassing haha)
-Source-code beschikbaar
-Goede toolset

Cons:
-Moeilijk te leren (volgens wat reddit posts)
-Minder goede documentatie.

Ik ben zelf voor Godot of Unity, maar ga rondkijken en kijk ook vooral naar andere engines. Schrijf in de comments je preferentie en/of onderbouwing voor andere game engine

**Comment by timmeej** [comment]
Naar mijn mening ziet godot er wel goed uit voor als we een 2d game willen maken, in godot kan je namelijk exclusief in 2d scenes werken wat in unity volgensmij niet kan waardoor je je 2d game eigenlijk in een 3d wereld moet maken wat misschien soms irritant kan zijn. Ook is godot voor beginnende devs makkelijker in te komen en gratis :)
